###
GET http://localhost:3000/about


###
GET http://localhost:3000/api/v1/workouts

###
DELETE http://localhost:3000/api/v1/workouts/1

###
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json

{
      "title": "Chest Press",
      "duration": 45,
      "location": "Gym NP",
      "type": "Strength Training",
      "date": "12/17/2024",
      "handle": "@JustinFeinman"
}
###
POST http://localhost:3000/api/v1/workouts
Content-Type: application/json

{
        "title": "q",
        "date": "10/10/2021",
        "duration": 0,
        "location": "1",
        "type": "1",
        "handle": "@JustinFeinman"
}
###
DELETE http://localhost:3000/api/v1/workouts/11

###
POST http://localhost:3000/api/v1/workouts/seed