###
https://google.com

###
POST https://dummyjson.com/products/add
MyHeader: MyValue

{
    "title": "Green Lip Stick",
    "price": 10.99,
    "description": "This is a green lip stick",
    "image": "https://dummyimage.com/300x300",
}
###
GET http://localhost:3000/about


###
GET http://localhost:3000/users

###
DELETE http://localhost:3000/users/1


